// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package gpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CardRefushTy int32

const (
	CardRefushTy_CR_None  CardRefushTy = 0
	CardRefushTy_CR_Daily CardRefushTy = 1
)

var CardRefushTy_name = map[int32]string{
	0: "CR_None",
	1: "CR_Daily",
}

var CardRefushTy_value = map[string]int32{
	"CR_None":  0,
	"CR_Daily": 1,
}

func (x CardRefushTy) String() string {
	return proto.EnumName(CardRefushTy_name, int32(x))
}

func (CardRefushTy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type PItem struct {
	// 字典id
	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	// 道具数量
	Num int32 `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`
	// 实例id
	InsId string `protobuf:"bytes,3,opt,name=InsId,proto3" json:"InsId,omitempty"`
	// 等级
	Lv                   int32    `protobuf:"varint,4,opt,name=Lv,proto3" json:"Lv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PItem) Reset()         { *m = PItem{} }
func (m *PItem) String() string { return proto.CompactTextString(m) }
func (*PItem) ProtoMessage()    {}
func (*PItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *PItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PItem.Unmarshal(m, b)
}
func (m *PItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PItem.Marshal(b, m, deterministic)
}
func (m *PItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PItem.Merge(m, src)
}
func (m *PItem) XXX_Size() int {
	return xxx_messageInfo_PItem.Size(m)
}
func (m *PItem) XXX_DiscardUnknown() {
	xxx_messageInfo_PItem.DiscardUnknown(m)
}

var xxx_messageInfo_PItem proto.InternalMessageInfo

func (m *PItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PItem) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *PItem) GetInsId() string {
	if m != nil {
		return m.InsId
	}
	return ""
}

func (m *PItem) GetLv() int32 {
	if m != nil {
		return m.Lv
	}
	return 0
}

type PCard struct {
	Id        string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	BigImgUrl string `protobuf:"bytes,2,opt,name=BigImgUrl,proto3" json:"BigImgUrl,omitempty"`
	ImgUrl    string `protobuf:"bytes,3,opt,name=ImgUrl,proto3" json:"ImgUrl,omitempty"`
	// 卡片的刷新类型
	RefushTy CardRefushTy `protobuf:"varint,4,opt,name=RefushTy,proto3,enum=CardRefushTy" json:"RefushTy,omitempty"`
	// 卡片的到期时间
	Timeout int32 `protobuf:"varint,5,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	// 卡片的刷新奖励
	Items []*PItem `protobuf:"bytes,6,rep,name=Items,proto3" json:"Items,omitempty"`
	// 刷新时间（上一次领取时间
	RefushTime           int32    `protobuf:"varint,7,opt,name=RefushTime,proto3" json:"RefushTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PCard) Reset()         { *m = PCard{} }
func (m *PCard) String() string { return proto.CompactTextString(m) }
func (*PCard) ProtoMessage()    {}
func (*PCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *PCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PCard.Unmarshal(m, b)
}
func (m *PCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PCard.Marshal(b, m, deterministic)
}
func (m *PCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PCard.Merge(m, src)
}
func (m *PCard) XXX_Size() int {
	return xxx_messageInfo_PCard.Size(m)
}
func (m *PCard) XXX_DiscardUnknown() {
	xxx_messageInfo_PCard.DiscardUnknown(m)
}

var xxx_messageInfo_PCard proto.InternalMessageInfo

func (m *PCard) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PCard) GetBigImgUrl() string {
	if m != nil {
		return m.BigImgUrl
	}
	return ""
}

func (m *PCard) GetImgUrl() string {
	if m != nil {
		return m.ImgUrl
	}
	return ""
}

func (m *PCard) GetRefushTy() CardRefushTy {
	if m != nil {
		return m.RefushTy
	}
	return CardRefushTy_CR_None
}

func (m *PCard) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *PCard) GetItems() []*PItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *PCard) GetRefushTime() int32 {
	if m != nil {
		return m.RefushTime
	}
	return 0
}

func init() {
	proto.RegisterEnum("CardRefushTy", CardRefushTy_name, CardRefushTy_value)
	proto.RegisterType((*PItem)(nil), "PItem")
	proto.RegisterType((*PCard)(nil), "PCard")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcf, 0x6a, 0x83, 0x40,
	0x10, 0x87, 0xab, 0x76, 0x35, 0x4e, 0x6c, 0x2a, 0x4b, 0x29, 0x5b, 0x08, 0x45, 0x72, 0x32, 0x3d,
	0x78, 0x48, 0x8f, 0xbd, 0xc5, 0x42, 0x59, 0x08, 0xa9, 0x2c, 0xe9, 0xa5, 0x97, 0x10, 0xeb, 0xc6,
	0x0a, 0xae, 0x1b, 0xfc, 0x13, 0xc8, 0x2b, 0xf5, 0x69, 0xfa, 0x48, 0xc5, 0xd5, 0x34, 0xde, 0x76,
	0xbe, 0xe1, 0xf7, 0xcd, 0xce, 0x80, 0xf3, 0x25, 0x85, 0x90, 0x45, 0x70, 0x28, 0x65, 0x2d, 0x67,
	0xef, 0x80, 0x22, 0x5a, 0x73, 0x81, 0x27, 0xa0, 0xd3, 0x84, 0x68, 0x9e, 0xe6, 0x23, 0xa6, 0xd3,
	0x04, 0xbb, 0x60, 0xac, 0x1b, 0x41, 0x74, 0x05, 0xda, 0x27, 0xbe, 0x03, 0x44, 0x8b, 0x8a, 0x26,
	0xc4, 0xf0, 0x34, 0xdf, 0x66, 0x5d, 0xd1, 0xe6, 0x56, 0x47, 0x72, 0xdd, 0xe5, 0x56, 0xc7, 0xd9,
	0xaf, 0x06, 0x28, 0x0a, 0x77, 0x65, 0x32, 0x30, 0xda, 0xca, 0x38, 0x05, 0x7b, 0x99, 0xa5, 0x54,
	0xa4, 0x1f, 0x65, 0xae, 0xbc, 0x36, 0xbb, 0x00, 0x7c, 0x0f, 0x66, 0xdf, 0xea, 0xf4, 0x7d, 0x85,
	0xe7, 0x30, 0x62, 0x7c, 0xdf, 0x54, 0xdf, 0x9b, 0x93, 0x9a, 0x32, 0x59, 0xdc, 0x04, 0xad, 0xfe,
	0x0c, 0xd9, 0x7f, 0x1b, 0x13, 0xb0, 0x36, 0x99, 0xe0, 0xb2, 0xa9, 0x09, 0x52, 0xff, 0x39, 0x97,
	0x78, 0x0a, 0xa8, 0x5d, 0xb2, 0x22, 0xa6, 0x67, 0xf8, 0xe3, 0x85, 0x19, 0xa8, 0x9d, 0x59, 0x07,
	0xf1, 0x23, 0x40, 0xef, 0xc8, 0x04, 0x27, 0x96, 0x8a, 0x0e, 0xc8, 0xd3, 0x1c, 0x9c, 0xe1, 0x44,
	0x3c, 0x06, 0x2b, 0x64, 0xdb, 0xb5, 0x2c, 0xb8, 0x7b, 0x85, 0x1d, 0x18, 0x85, 0x6c, 0xfb, 0xba,
	0xcb, 0xf2, 0x93, 0xab, 0x2d, 0x1f, 0x3e, 0x51, 0xf0, 0x92, 0x1e, 0xe2, 0x1f, 0xfd, 0xf6, 0x4d,
	0xca, 0x34, 0xe7, 0x41, 0xd4, 0x9e, 0x39, 0x6e, 0xf6, 0xb1, 0xa9, 0x0e, 0xfe, 0xfc, 0x17, 0x00,
	0x00, 0xff, 0xff, 0x6b, 0xc9, 0x01, 0xbc, 0x80, 0x01, 0x00, 0x00,
}
